### ISSUE TITLE
Uncaught Error: Cannot find module 'truffle-hdwallet-provider-privkey'

### ISSUE THREAD

**Issue by ghost** [rhlsthrm/truffle-hdwallet-provider-privkey#14]
I tried to require this hdprovider but it throws this error

**syntax**:  const HDWalletProvider = require("truffle-hdwallet-provider-privkey");

**error:**
`Uncaught Error: Cannot find module 'truffle-hdwallet-provider-privkey'
Require stack:
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at evalmachine.<anonymous>:0:26
    at sigintHandlersWrap (vm.js:272:15)
    at Script.runInContext (vm.js:127:14)
    at runScript (C:\Users\swiff\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\console.js:251:1)
    at Console.interpret (C:\Users\swiff\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\console.js:266:1)
    at bound (domain.js:427:14)
    at REPLServer.runBound [as eval] (domain.js:440:12)
    at REPLServer.onLine (repl.js:760:10)
    at REPLServer.emit (events.js:315:20)
    at REPLServer.EventEmitter.emit (domain.js:483:12)
    at REPLServer.Interface._onLine (readline.js:329:10)
    at REPLServer.Interface._line (readline.js:658:8)
    at REPLServer.Interface._ttyWrite (readline.js:1003:14)
    at REPLServer.self._ttyWrite (repl.js:850:9)
    at ReadStream.onkeypress (readline.js:205:10)
    at ReadStream.emit (events.js:315:20)
    at ReadStream.EventEmitter.emit (domain.js:483:12)
    at emitKeys (internal/readline/utils.js:335:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1137:36)
    at ReadStream.emit (events.js:315:20)
    at ReadStream.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at ReadStream.Readable.push (_stream_readable.js:212:10)
    at TTY.onStreamRead (internal/stream_base_commons.js:186:23)
    at TTY.callbackTrampoline (internal/async_hooks.js:120:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
}`

**Comment by rhlsthrm** [comment]
Hi @david0i, this package is no longer needed. You can provide private keys directly using the official Truffle hdwallet-provider: https://github.com/trufflesuite/truffle/tree/develop/packages/hdwallet-provider.
