### ISSUE TITLE
Error: Web3ProviderEngine does not support synchronous requests.

### ISSUE THREAD

**Issue by lakamsani** [rhlsthrm/truffle-hdwallet-provider-privkey#5]
Hi, when trying to use web3 using the steps shown [here](https://www.npmjs.com/package/truffle-hdwallet-provider-privkey#web3-provider) like this `web3.eth.getBalance(addr)` , getting this error:

```bash
Error: Web3ProviderEngine does not support synchronous requests.
    at Web3ProviderEngine.Object.<anonymous>.Web3ProviderEngine.send (/Users/vamsee/Development/blockchain/pulse/server/node_modules/web3-provider-engine/index.js:54:9)
    at RequestManager.Object.<anonymous>.RequestManager.send (/Users/vamsee/Development/blockchain/pulse/server/node_modules/web3/lib/web3/requestmanager.js:58:32)
    at Eth.send [as getBalance] (/Users/vamsee/Development/blockchain/pulse/server/node_modules/web3/lib/web3/method.js:145:58)
    at BlockchainHelper.getETHBalance (/Users/vamsee/Development/blockchain/pulse/server/src/lib/BlockchainWalletHelper.js:39:44)
    at Object.<anonymous>.test (/Users/vamsee/Development/blockchain/pulse/server/__tests__/unit/BlockchainHelperTests.js:50:26)
    at Object.asyncFn (/Users/vamsee/Development/blockchain/pulse/server/node_modules/jest-jasmine2/build/jasmine_async.js:124:345)
    at resolve (/Users/vamsee/Development/blockchain/pulse/server/node_modules/jest-jasmine2/build/queue_runner.js:46:12)
    at new Promise (<anonymous>)
    at mapper (/Users/vamsee/Development/blockchain/pulse/server/node_modules/jest-jasmine2/build/queue_runner.js:34:499)
    at promise.then (/Users/vamsee/Development/blockchain/pulse/server/node_modules/jest-jasmine2/build/queue_runner.js:74:39)
```
But it works fine if instead I create a separate web3 like this: 
`const web3 = new Web3(new Web3.providers.HttpProvider(urlOrEngine))` .  Any thoughts on how to make them work the same so we don't need to create another web3?

**Comment by rhlsthrm** [comment]
Thanks, I never knew that this workaround existed. I have always used the callback-based approach when using this package, i.e.

```
web3.eth.getBalance(addr, (err, balance => {
  console.log(balance)
})
```

It looks like this is a limitation of the Web3ProviderEngine package itself, so I'm not sure there is anything we can do in this package.
